# SPDX-License-Identifier: GPL-2.0+

variables:
  DEFAULT_ALL_TAG: "all"
  DEFAULT_ARM64_TAG: "arm64"
  DEFAULT_FAST_ARM64_TAG: "fast arm64"
  DEFAULT_AMD64_TAG: "amd64"
  DEFAULT_FAST_AMD64_TAG: "fast amd64"
  MIRROR_DOCKER: docker.io
  SJG_LAB: ""
  PLATFORM: linux/amd64,linux/arm64

default:
  tags:
    - ${DEFAULT_ALL_TAG}

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == 'tbottesting'
    - when: never

# Grab our configured image.  The source for this is found
# in the u-boot tree at tools/docker/Dockerfile
image: ${MIRROR_DOCKER}/trini/u-boot-gitlab-ci-runner:jammy-20240911.1-08Dec2024

# We run some tests in different order, to catch some failures quicker.
stages:
  - tbot-lab

tbottest-test-all-boards:
  stage: tbot-lab
  before_script:
    - echo "before script"
    - pwd
    - whoami
    # install tbot dependencies
    - python -m pip install --upgrade pip
    - pip3 install --user pytest mypy paramiko termcolor2 pyserial coverage pytest-cov
    - pip3 list
    # configure ssh
    # https://gitlab.com/gitlab-examples/ssh-private-key/-/blob/master/.gitlab-ci.yml?ref_type=heads
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_UB_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - git config --global user.email "darth@empire.com"
    - git config --global user.name "Darth Vader"
    - |
      cat >>~/.ssh/config <<END
        Host $SSH_UB_HOST
          HostName $SSH_UB_HOST
          User $SSH_UB_USER
          IdentityFile ~/.ssh/staging.key
          StrictHostKeyChecking no

        Host ubtestinglab
          HostName ubtestinglab
          User $SSH_UB_USER
          ProxyJump $SSH_UB_HOST
          IdentityFile ~/.ssh/staging.key
          StrictHostKeyChecking no

     END

   - export COLUMNS=160
   - export PYTHONPATH=/home/uboot/.local/lib/python3.10/site-packages

   # Test if ssh works
   - echo "--------------------- try ssh ------------------"
   - ssh -o StrictHostKeyChecking=no -i ~/.ssh/staging.key ${SSH_HOST} /home/pi/hello.sh
   - ssh -o StrictHostKeyChecking=no -i ~/.ssh/staging.key pi@ubtestinglab /home/pi/hello.sh

  script:
    - echo "in script"
    - pwd
    - whoami
    # install tbot dependencies
    - python -m pip install --upgrade pip
    - pip3 install --user pytest mypy paramiko termcolor2 pyserial coverage pytest-cov
    - pip3 list
  after_script:
    - echo "after script"
    - pwd
      #- cp -v /tmp/${TEST_PY_BD}/*.{html,css,xml} .
